### ISSUE TITLE
Add more highlighter tests

### ISSUE THREAD

**Issue by vpetrovykh** [edgedb/edgedb-editor-plugin#6]
More tests are needed for both EdgeQL and eschema highlighters.

eschema:
* [ ] test all keywords
* [ ] `atom`
* [x] `concept`
* [ ] `link`
* [ ] `linkproperty`

EdgeQL:
* [ ] DDL syntax
* [ ] `WITH`
* [x] `SELECT`
* [ ] `GROUP`
* [ ] `UPDATE`
* [ ] `INSERT`
* [ ] `DELETE`

**Comment by 1st1** [comment]
@vpetrovykh Please update this issue.

**Comment by 1st1** [comment]
I think we can just close this one. Will add more tests as we go.
